name: dotlottie_loader
description: dotLottieLoader is a library to help downloading and deflating a .lottie file.
version: 0.0.6
# homepage: https://github.com/sartajroshan/dotlottieloader-flutter
repository: https://github.com/sartajroshan/dotlottieloader-flutter
issue_tracker: https://github.com/sartajroshan/dotlottieloader-flutter/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  archive: '>=4.0.0 <5.0.0'
  web: '>=1.0.0 <2.0.0'
  http: '>=1.3.0 <2.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1
